name: flutter_advanced_html_editor
description: A powerful and customizable HTML editor for Flutter.
version: 1.0.0
homepage: https://github.com/alheki/flutter_advanced_html_editor
repository: https://github.com/alheki/flutter_advanced_html_editor
issue_tracker: https://github.com/alheki/flutter_advanced_html_editor/issues
documentation: https://github.com/alheki/flutter_advanced_html_editor#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

